In [1]:
import os
import sys
sys.path.append(os.path.dirname(os.getcwd()))

import numpy as np
from functools import partial

from bases import fourier_basis
from otrhogonalizations import gram_schmidt, powered_gram_schmidt

deg = 5
basis = partial(fourier_basis, degree=deg)

In [2]:
Ub = np.array([[1/2, -1/2, -1/2, 1/2],
              [1/2, 1/2, 1/2, 1/2],
              [1/2, 1/2, -1/2, -1/2],
              [1/2, -1/2, 1/2, -1/2],])
Ub.T @ Ub

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
U = np.eye(2*deg+1)
U[:4,:4] = Ub
U[4:8,4:8] = Ub
U.shape

(11, 11)

In [4]:
U.T @ U

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
V = np.empty(U.shape)

for k in range(V.shape[0]):
    V[k] = gram_schmidt(U, k)

V

array([[ 0.5, -0.5, -0.5,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5, -0.5, -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5, -0.5,  0.5, -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5, -0.5, -0.5,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5,  0.5,  0.5,  0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5,  0.5, -0.5, -0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5, -0.5,  0.5, -0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ]])

In [6]:
x = np.random.rand(5)
basis(x).shape

(11, 5)

In [7]:
x[None,...].shape

(1, 5)

In [8]:
V = np.empty(U.shape).astype('complex128')
U = U.astype('complex128')

for k in range(V.shape[0]):
    V[k] = powered_gram_schmidt(U, k, basis, 3)

V.shape

(11, 11)

In [9]:
np.sum(U-V)

(-8.881784197001252e-16+6.310887241768095e-30j)

In [10]:
A = np.random.rand(10,10)
A.shape

(10, 10)

In [11]:
np.random.rand(A.shape[0], A.shape[1]).shape

(10, 10)