In [1]:
import numpy as np

In [4]:
shape = (10, 10)
V = np.random.rand(shape[0], shape[1])
U = 1j * np.random.rand(shape[0], shape[1])

In [5]:
V

array([[0.62569584, 0.50268082, 0.71988847, 0.8874661 , 0.30523513,
        0.69104131, 0.29380557, 0.95665261, 0.79749961, 0.12289854],
       [0.0618486 , 0.79751081, 0.65089784, 0.05351576, 0.15388693,
        0.45930733, 0.59313359, 0.82350748, 0.20222302, 0.25247916],
       [0.44784817, 0.64670021, 0.84618961, 0.56232277, 0.27550921,
        0.20765852, 0.34590044, 0.91482288, 0.40965741, 0.91193977],
       [0.27110244, 0.54368195, 0.6715448 , 0.34896959, 0.88552088,
        0.45494069, 0.11259102, 0.76133564, 0.43235436, 0.95998254],
       [0.01735004, 0.01341641, 0.47372086, 0.05690661, 0.56812378,
        0.04870083, 0.78213432, 0.16918253, 0.6481764 , 0.67179585],
       [0.43624969, 0.77379854, 0.30157748, 0.55023586, 0.23858943,
        0.13316835, 0.61050199, 0.10286318, 0.91861617, 0.37065037],
       [0.90854671, 0.82789287, 0.62368132, 0.48487579, 0.81808621,
        0.39748531, 0.16065036, 0.2615481 , 0.24094223, 0.70993645],
       [0.80691058, 0.78230865, 0.8549131

In [6]:
U

array([[0.+0.30053323j, 0.+0.28991846j, 0.+0.66742615j, 0.+0.47418037j,
        0.+0.69540634j, 0.+0.95129227j, 0.+0.99179378j, 0.+0.05263508j,
        0.+0.75331603j, 0.+0.75415806j],
       [0.+0.65373802j, 0.+0.42140709j, 0.+0.98300753j, 0.+0.77367524j,
        0.+0.17231499j, 0.+0.62710808j, 0.+0.15745069j, 0.+0.05680381j,
        0.+0.92706366j, 0.+0.76752686j],
       [0.+0.43589719j, 0.+0.90579296j, 0.+0.16409815j, 0.+0.24571307j,
        0.+0.02846516j, 0.+0.56733027j, 0.+0.98867505j, 0.+0.45042521j,
        0.+0.23428089j, 0.+0.62403337j],
       [0.+0.41535598j, 0.+0.73592571j, 0.+0.66739183j, 0.+0.41716766j,
        0.+0.37229111j, 0.+0.22315634j, 0.+0.34261913j, 0.+0.17699016j,
        0.+0.01743372j, 0.+0.27044983j],
       [0.+0.55671058j, 0.+0.46890625j, 0.+0.99054002j, 0.+0.67848249j,
        0.+0.44669174j, 0.+0.90715517j, 0.+0.26138605j, 0.+0.3667276j ,
        0.+0.99875307j, 0.+0.75411521j],
       [0.+0.92489484j, 0.+0.71614605j, 0.+0.59768391j, 0.+0.72592028j,
   

In [9]:
Z = U + V
Z

array([[0.62569584+0.30053323j, 0.50268082+0.28991846j,
        0.71988847+0.66742615j, 0.8874661 +0.47418037j,
        0.30523513+0.69540634j, 0.69104131+0.95129227j,
        0.29380557+0.99179378j, 0.95665261+0.05263508j,
        0.79749961+0.75331603j, 0.12289854+0.75415806j],
       [0.0618486 +0.65373802j, 0.79751081+0.42140709j,
        0.65089784+0.98300753j, 0.05351576+0.77367524j,
        0.15388693+0.17231499j, 0.45930733+0.62710808j,
        0.59313359+0.15745069j, 0.82350748+0.05680381j,
        0.20222302+0.92706366j, 0.25247916+0.76752686j],
       [0.44784817+0.43589719j, 0.64670021+0.90579296j,
        0.84618961+0.16409815j, 0.56232277+0.24571307j,
        0.27550921+0.02846516j, 0.20765852+0.56733027j,
        0.34590044+0.98867505j, 0.91482288+0.45042521j,
        0.40965741+0.23428089j, 0.91193977+0.62403337j],
       [0.27110244+0.41535598j, 0.54368195+0.73592571j,
        0.6715448 +0.66739183j, 0.34896959+0.41716766j,
        0.88552088+0.37229111j, 0.45494069+0.

In [11]:
T = Z/np.linalg.norm(Z, axis=0)

In [14]:
np.linalg.norm(T[:,0])

1.0